services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: media2ha-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: media2ha-ha
    restart: unless-stopped
    depends_on:
      - mosquitto
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant:/config
    environment:
      - TZ=Europe/Paris
