name: Release to Play Store

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: MiCodesOrg/.github/.github/workflows/android-release.yml@main
    with:
      package_name: fr.micodes.media2ha
      gradle_command: ./gradlew :app:bundleRelease :app:assembleRelease
      apk_path: app/build/outputs/apk/release/app-release.apk
    secrets: inherit
